### ISSUE TITLE
Relate option category with parent product intead of product versions

### ISSUE THREAD

**Issue by SimonRuaGitHub** [SimonRuaGitHub/rd-company-hq#23]
## Story Description

As a company stock admin, I want to be able to create option categories related to parent products and vice-versa. So users can visualize option sections when ordering a set of products.

### Successful Scenarios:

* **Scenario: Create an option category related to multiple existing parent products**

Given the type of user is a company stock user
When the user saves an option category related to multiple exiting parent products from the same company
Then the user should be able to see a successful message 
And all the attributes inserted for the created product

* **Scenario: Create a parent product related to multiple option categories**

Given the type of user is a company stock user
When the user saves a parent product related to multiple existing option categories from the same company
Then the user should be able to see a successful message 
And all the attributes inserted for the created option category

### Failure Scenarios:

* **Scenario: Create option category related to multiple unexisting parent products**

Given the type of user is a company stock user
When the user saves an option category related to multiple unexisting parent products
Then the user should be able to see an error message

* **Scenario: Create parent product related to multiple unexisting option categories**

Given the type of user is a company stock user
When the user saves a parent product related to multiple unexisting option categories
Then the user should be able to see an error message

* **Scenario: Create an option category related to parent products from another company**

Given the type of user is a company stock user
When the user saves an option category related to parent products from another company
Then the user should be able to see an error message

* **Scenario: Create a parent product related to option categories from another company**

Given the type of user is a company stock user
When the user saves a parent product related to option categories from other companies
Then the user should be able to see an error message

* **Scenario: Create either parent product or option categories with invalid related data**

Given the type of user is a company stock user
When the user saves a(n) `<uniqueEntity>` related to multiple `<manyRelatedEntities>`
Then the user should be able to see an error message

|uniqueEntity|manyRelatedEntities|
|parent product|option categories|
|option category|parent products|

_**invalid data: Special characters instead of numerical values**_

## Tasks

- [x] Modify model entities relationship for ProductVersion, ParentProduct, and OptionCategories
- [x] Modify OptionCategory and Parent product mappers
- [x] Modify DTO classes
- [x] Implement exceptions
- [x] Unit tests
- [x] Integration tests
