### ISSUE TITLE
Relate Products with Racks

### ISSUE THREAD

**Issue by SimonRuaGitHub** [SimonRuaGitHub/rd-company-hq#29]
## Story Description
As a company stock admin, I want to be able to create products and racks related to each other. So users can visualize products inside racks.

### Successful Scenarios:

* **Create a product with multiple racks** : Successful message 
* **Create a rack with multiple products** : Successful message

## Failure Scenarios

* **Create a product with unexisting racks** : Error message
* **Create a rack with unexisting products** : Error message
* **Create a product with racks from another company** : Error message
* **Create a rack with products from another company** : Error message
* **Create a product with rack with invalid related data** : Error message
* **Create a rack with product invalid related data** : Error message

_**invalid data: Special characters instead of numerical values**_

## Tasks

- [x] Related Racks with products 
- [x] Map rack and products 
- [x] Validate racks and products from another company
- [x] Create/Use exceptions
- [x] Integration tests
