### ISSUE TITLE
Create product versions

### ISSUE THREAD

**Issue by SimonRuaGitHub** [SimonRuaGitHub/rd-company-hq#30]
## Story Description
As a company stock admin, I want to be able to create product versions. So users select the proper version with corresponding attributes (mainly: price, name, and description)

### Successful Scenarios: 📗 

* Create only one product version related to a parent product: Successful message ✅ 
* Create product versions related to the same parent product: Successful message ✅ 
(Condition: first product is available, the other products should not be available)

Return: saved product version 

### Failure Scenarios: 🔴 

* Create a product version invalid data : Error message ✅ 
_**invalid data: Special characters instead of numerical values**_
* Create a product version with existing name or description : Error message ✅ 
* Create a product version with an unexisting parent product : Error message ✅ 
* Create a product version with multiple parent products : Error message ✅ 
* Create a product version without parent product : Error message ✅ 
* Create multiple available product versions related to the same parent product : Error message ✅ 

## Tasks

- [x] Map product version
- [x] Create product version DTO
- [x] Implement controller
- [x] Implement Service
- [x] Validate multiple product versions available for the same parent product
- [x] Create/Use exceptions
- [x] Integration tests
