### ISSUE TITLE
Create Delivery Basic food Wireframes 

### ISSUE THREAD

**Issue by SimonRuaGitHub** [SimonRuaGitHub/rd-company-hq#31]
### Main Features:

* User arrives for onboarding
* User fills up personal info and payment methods
* User selects a product and pays
* User schedules an order for different days
* User fonds credits from payment method to manage money employed in the App

### Tasks:

- [ ] Create flow diagrams for each feature
- [ ] Identify information to show up in each feature (as images, descriptions, labels....etc)
- [ ] Create corresponding wireframes
- [ ] Connect each wireframe and create corresponding flows

### Conditions:

- [ ] Use 3 colors only (preferred blue or purple as primary colors)
- [ ] Define a specific font type
- [ ] Response web design
