### ISSUE TITLE
Create product availabilities

### ISSUE THREAD

**Issue by SimonRuaGitHub** [SimonRuaGitHub/rd-company-hq#32]
## Story Description
As a company stock admin, I want to register product quantity on stock depending on the company site

### Successful Scenarios 📗  

- Create a product available for the corresponding company site and product version ✅ 
Return: Successful Message 

### Failure Scenarios: 🧧 

- Create an available product with invalid data ✅ 
- Create an available product for an existing company site and product version ✅ 
- Create an available product without product version ✅ 
- Create an available product with an unexisting product version ✅ 

Return for all: Error message

## Tasks

- [x] Implement product availability service
- [x] Create product availability DTO class and declare object inside product version DTO class
- [x] Map product availability DTO object to the corresponding entity model 
- [x] Validate business scenarios
- [x] Implement unit tests

Note: the implementation for the company site validation existence through a Rest API will be covered in other tickets, for now it is possible to add any company site
